version: '3.3'

services:
  userregistrationdb:
    container_name: userregistrationdb
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=userregistrations
      - MONGO_INITDB_ROOT_USERNAME=my_ms
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - my_ws
  authorizationdb:
    container_name: authorizationdb
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=password123
    ports:
      - '6379'
    networks:
      - my_ws
  userauthorizationtbackend:
    container_name: userauthorizationtbackend
    build: ./../car-now-user-authentication-service
    ports:
      - 9002:9002
    depends_on:
      - authorizationdb
    networks:
      - my_ws
  usermanagementdb:
    container_name: usermanagementdb
    image: mysql:5
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rentalCarService
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    networks:
      - my_ws
  signupmanagementbackend:
    container_name: signupmanagementbackend
    build: ./../car-now-user-signup-service
    ports:
      - 9010:9001
    depends_on:
      - userregistrationdb
      - rabbit1
      - rabbit2
    networks:
      - my_ws
  angular_frontend:
    container_name: angular_frontend
    build: ./../CarRentalAngularApp/
    ports:
      - 80:80
    depends_on:
      - signupmanagementbackend
    networks:
      - my_ws
  currency_converter_sw:
    container_name: currency_ws
    build: ./../CurrencyConverterWebservice
    ports:
      - 9090:80
    networks:
      - my_ws
  rabbit1:
    image: levvel/rabbitclusternode
    hostname: rabbit1
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_ws

  rabbit2:
    image: levvel/rabbitclusternode
    hostname: rabbit2
    links:
      - rabbit1
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit1
      - RAM_NODE=true
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - my_ws
networks:
  my_ws:
    driver: bridge
