version: '3.3'

services:
  db:
    container_name: rental_db
    image: mysql:5
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rentalCarService
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    networks:
      - my_ws
  backend_spring:
    container_name: spring_container
    build: ./../Car_Rental_WS/
    ports:
      - 8443:8443
    depends_on:
      - db
    networks:
      - my_ws
networks:
  my_ws:
    driver: bridge
