//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.30 at 09:01:25 PM CEST 
//


package fh.se.car.rental.fh.currency.ws.client.helper;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="convertCurrencyResult" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "convertCurrencyResult"
})
@XmlRootElement(name = "convertCurrencyResponse")
public class ConvertCurrencyResponse {

    protected double convertCurrencyResult;

    /**
     * Gets the value of the convertCurrencyResult property.
     * 
     */
    public double getConvertCurrencyResult() {
        return convertCurrencyResult;
    }

    /**
     * Sets the value of the convertCurrencyResult property.
     * 
     */
    public void setConvertCurrencyResult(double value) {
        this.convertCurrencyResult = value;
    }

}
